name: 🚀 Tarea de Despliegue

on:
   push:
     branches:
       Johnatan

jobs:
  deploy:
    name: 🎉 Trabajo de Despliegue
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Obteniendo el código más reciente
        uses: actions/checkout@v4

      - name: 📂 Sincronizando archivos via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server:  ftp-jojoapp.alwaysdata.net # Change if using another host
          username: jojoapp
          password: 3108787231Jc.
          server-dir: www/ # Replace with your correct path
          protocol: ftps
          timeout: 86400000
          log-level: standard
          exclude: |
           .git/**
           .github/**
